'use client';

import { useEffect, useRef, useState } from 'react';
import RailNav from '@/components/rail/RailNav';
import { useMusic } from './MusicProvider';
import { formatTime, trackKey } from '@/lib/musicCore';

function TrackList({ tracks = [], music }) {
  return <ol className="mu-tracks">{tracks.map((track, i) => <li key={trackKey(track) || i} className={trackKey(track) === music.activeKey ? 'is-active' : ''}>
    <button className="mu-track-main" type="button" onClick={() => music.playTrack(track, tracks, true)}><span className="mu-track-index">{trackKey(track) === music.activeKey && music.isPlaying ? '♫' : i + 1}</span><span><strong>{track.title || 'Untitled'}</strong><small>{track.artists || track.subtitle || ''}</small></span><span className="mu-duration">{track.durationLabel || ''}</span></button>
    <button type="button" aria-label={`Favourite ${track.title}`} title="Favourite" aria-pressed={music.favoriteSet.has(trackKey(track))} onClick={() => music.toggleFavorite(track)}>{music.favoriteSet.has(trackKey(track)) ? '★' : '☆'}</button>
    <button type="button" aria-label={`Add ${track.title} to queue`} title="Add to queue" onClick={() => music.addToQueue(track)}>＋</button>
  </li>)}</ol>;
}
function CollectionGrid({ items = [], kind = 'album', onOpen }) {
  return <div className="mu-collection-grid">{items.map((item) => <button key={item.id || item.title || item.name} type="button" className="mu-collection" onClick={() => onOpen(item)}>{item.image ? <img src={item.image} alt="" loading="lazy"/> : <span className="mu-art-fallback">♫</span>}<strong>{item.title || item.name}</strong><small>{item.artists || item.subtitle || `${item.songCount || item.count || ''} ${kind === 'artist' ? '' : 'tracks'}`}</small></button>)}</div>;
}

export default function MusicCurtains() {
  const m = useMusic();
  const [queueOpen, setQueueOpen] = useState(false), [focus, setFocus] = useState(false), [fontSize, setFontSize] = useState(30);
  const [libraryTab, setLibraryTab] = useState('albums');
  const pane = useRef(null);
  const view = m.centerTab === 'lyrics' ? libraryTab : m.centerTab;
  const selected = m.selectedCollection;
  const detail = selected && ((view === 'albums' && selected.type === 'album') || (view === 'playlists' && selected.type === 'playlist') || (view === 'artists' && selected.type === 'artist'));
  useEffect(() => { if (m.facet.id !== 'albums') m.loadFacet('albums'); }, []); // independent album catalogue, not home summaries
  function navigate(id) { m.setCenterTab(id); if (id !== 'lyrics') setLibraryTab(id); setFocus(false); }
  useEffect(() => { pane.current?.scrollTo({ top: 0 }); }, [view, selected?.id]);
  function back() { if (selected.type === 'playlist') { m.backToAlbums(); navigate('playlists'); } else m.backToAlbums(); }
  const songs = view === 'search' ? m.searchResults.songs : view === 'tracks' ? m.allShelfSongs : m.favoriteTracks;
  const lyricsRows = m.syncedLyricLines.length ? m.lyricRows : m.plainLyricLines;
  return (
    <main className={`mu jv-rail-shift ${focus ? 'mu-focus' : ''} ${m.centerTab === 'lyrics' ? 'mu-mobile-lyrics' : ''}`}>
      <RailNav onOpenSearch={() => { navigate('search'); }} />
      <header className="mu-header"><div><p className="mu-eyebrow">JaSH ViBeS</p><h1>Lyric Lounge</h1></div><label className="mu-search"><span className="sr-only">Search music</span><input placeholder="Search songs, albums, artists…" value={m.query} onFocus={() => navigate('search')} onChange={(e) => { m.setQuery(e.target.value); navigate('search'); }}/></label><div className="mu-header-actions"><button type="button" onClick={() => { setFocus(!focus); m.setCenterTab('lyrics'); }}>Lyrics focus</button><button type="button" onClick={() => setQueueOpen(true)}>Queue · {m.queueTracks.length}</button></div></header>
      <nav className="mu-mobile-nav" aria-label="Music views">{['lyrics', 'albums', 'tracks', 'playlists'].map((tab) => <button key={tab} type="button" aria-pressed={m.centerTab === tab} onClick={() => navigate(tab)}>{tab.charAt(0).toUpperCase() + tab.slice(1)}</button>)}</nav>
      <div className="mu-workspace">
        <aside className="mu-library" aria-label="Music library"><nav className="mu-library-tabs" aria-label="Browse music">{['albums', 'tracks', 'playlists'].map((tab) => <button key={tab} type="button" aria-pressed={view === tab} onClick={() => navigate(tab)}>{tab.charAt(0).toUpperCase() + tab.slice(1)}</button>)}</nav><div ref={pane} className="mu-library-body">
          {detail ? <section aria-label="Collection tracks"><button type="button" className="mu-back" onClick={back}>← Back to {selected.type === 'playlist' ? 'Playlists' : 'Albums'}</button><div className="mu-album-heading">{selected.image ? <img src={selected.image} alt=""/> : null}<div><p className="mu-eyebrow">{selected.type}</p><h2>{selected.title || selected.name}</h2><p>{selected.artists || ''}</p><small>{selected.tracks?.length || 0} loaded{selected.songCount && Number(selected.songCount) !== selected.tracks?.length ? ` / ${selected.songCount} declared` : ''}</small></div></div>
            {m.collectionStatus === 'loading' ? <div role="status" className="mu-inline-state">Loading the album’s actual tracks…</div> : null}
            {m.collectionStatus === 'error' ? <div role="alert" className="mu-inline-state is-error">{selected.error}<button type="button" onClick={() => selected.type === 'album' ? m.openAlbum(selected) : selected.type === 'artist' ? m.openArtist(selected) : m.openPlaylist(selected)}>Retry</button></div> : null}
            {selected.warning ? <p className="mu-inline-state">{selected.warning}</p> : null}
            {!!selected.tracks?.length && <button type="button" className="mu-play-all" onClick={() => m.playTrack(selected.tracks[0], selected.tracks, true)}>▶ Play all</button>}
            {selected.tracks?.length ? <TrackList tracks={selected.tracks} music={m}/> : m.collectionStatus === 'ready' ? <p className="mu-inline-state">The source did not supply tracks for this collection. Retry or select another album.</p> : null}
            {selected.albums?.length ? <CollectionGrid items={selected.albums} onOpen={m.openAlbum}/> : null}
          </section> : view === 'albums' ? <section><h2>Albums</h2><p className="mu-muted">Browse an album without replacing your playing queue.</p>{m.facet.status === 'loading' ? <p role="status" className="mu-inline-state">Loading albums…</p> : null}{m.facet.status === 'error' ? <div role="alert" className="mu-inline-state is-error">{m.facet.error}<button onClick={() => m.loadFacet('albums')} type="button">Retry</button></div> : null}<CollectionGrid items={m.facetLists.albums} onOpen={m.openAlbum}/><button type="button" className="mu-back" onClick={() => { navigate('artists'); m.loadFacet('artists'); }}>Browse artists →</button></section>
          : view === 'playlists' ? <section><h2>Playlists</h2><p className="mu-muted">Saved imports and source collections.</p><CollectionGrid items={[...m.facetLists.playlists, ...m.shelfCollections.filter((c) => c.type === 'playlist')]} kind="playlist" onOpen={m.openPlaylist}/>{!m.facetLists.playlists.length ? <p className="mu-inline-state">No imported playlists yet. Import Spotify metadata from the owner panel.</p> : null}<button type="button" className="mu-back" onClick={m.refreshImportedPlaylists}>Refresh playlists</button></section>
          : view === 'artists' ? <section><h2>Artists</h2><CollectionGrid items={m.facetLists.artists} kind="artist" onOpen={m.openArtist}/></section>
          : view === 'search' ? <section><h2>Search</h2>{m.searchStatus === 'loading' ? <p role="status" className="mu-inline-state">Searching…</p> : null}<TrackList tracks={songs} music={m}/><h3>Albums</h3><CollectionGrid items={m.searchResults.albums} onOpen={m.openAlbum}/><h3>Playlists</h3><CollectionGrid items={m.searchResults.playlists} kind="playlist" onOpen={m.openPlaylist}/><h3>Artists</h3><CollectionGrid items={m.searchResults.artists} kind="artist" onOpen={m.openArtist}/></section>
          : <section><h2>Tracks</h2><p className="mu-muted">Songs from your loaded shelves. Search to find more.</p><TrackList tracks={songs} music={m}/>{m.favoriteTracks.length ? <><h3>Favourites</h3><TrackList tracks={m.favoriteTracks} music={m}/></> : null}{m.recents.length ? <><h3>Recently played</h3><TrackList tracks={m.recents} music={m}/></> : null}</section>}
        </div></aside>
        <section className="mu-lyrics-stage" aria-label="Lyrics"><header><div><p className="mu-eyebrow">Now playing</p><h2>{m.playingTrack?.title || 'Let the lyrics take the stage'}</h2><p className="mu-muted">{m.playingTrack?.artists || 'Choose a song from an album, tracks or playlist.'}</p></div><div className="mu-lyrics-tools"><button type="button" aria-label="Smaller lyrics" onClick={() => setFontSize((v) => Math.max(20, v - 2))}>A−</button><button type="button" aria-label="Larger lyrics" onClick={() => setFontSize((v) => Math.min(48, v + 2))}>A＋</button><button type="button" aria-pressed={m.lyricAutoScroll} onClick={() => m.setLyricAutoScroll(!m.lyricAutoScroll)}>{m.lyricAutoScroll ? 'Following' : 'Resume follow'}</button></div></header>
          <div className="mu-lyric-scroll" onWheel={() => m.setLyricAutoScroll(false)} onTouchMove={() => m.setLyricAutoScroll(false)} style={{ '--mu-lyric-size': `${fontSize}px` }}>
            {m.lyricsStatus === 'loading' ? <p role="status" className="mu-inline-state">Finding lyrics for this song…</p> : null}
            {m.lyricsStatus === 'error' || m.lyricsStatus === 'not-found' ? <div className="mu-inline-state"><p>{m.lyricsData.message || 'Lyrics are not available from the current source.'}</p><button type="button" onClick={() => m.openLyrics(true)}>Retry lyrics</button></div> : null}
            {!m.playingTrack ? <div className="mu-lyric-empty"><span>♫</span><h3>Your music. Every line.</h3><p>Pick an album, choose a song, and read along.</p><button type="button" onClick={() => navigate('albums')}>Browse albums →</button></div> : null}
            <ol className="mu-lyric-lines">{lyricsRows.map((row, index) => <li key={`${m.activeKey}:${index}`} ref={row.state === 'current' ? m.activeLyricRef : undefined} data-state={row.state}>{row.time != null && m.syncedLyricLines.length ? <button type="button" onClick={() => m.seekTo(row.time)} title={`Seek to ${formatTime(row.time)}`}>{row.text}</button> : <span>{row.text}</span>}</li>)}</ol>
          </div>{m.syncedLyricLines.length ? <footer className="mu-lyrics-offset">Synced lyrics · offset <button type="button" onClick={() => m.setLyricOffset((v) => v - .25)}>−</button><span>{m.lyricOffset.toFixed(2)}s</span><button type="button" onClick={() => m.setLyricOffset((v) => v + .25)}>＋</button></footer> : m.lyricsStatus === 'ready' ? <footer className="mu-lyrics-offset">Plain lyrics · no timing data</footer> : null}
        </section>
      </div>
      <footer className="mu-playerbar" aria-label="Music player"><div className="mu-now-playing">{m.playingTrack?.image ? <img src={m.playingTrack.image} alt=""/> : <span>♫</span>}<div><strong>{m.playingTrack?.title || 'Nothing playing'}</strong><small>{m.playingTrack?.artists || 'Your queue stays independent of browsing'}</small></div></div><div className="mu-player-center"><div className="mu-transport"><button type="button" aria-pressed={m.shuffleEnabled} onClick={() => m.setShuffleEnabled(!m.shuffleEnabled)}>Shuffle</button><button type="button" aria-label="Previous track" onClick={m.playPrevious}>⏮</button><button type="button" className="mu-primary-play" aria-label={m.isPlaying ? 'Pause' : 'Play'} onClick={m.togglePlay}>{m.isPlaying ? 'Ⅱ' : '▶'}</button><button type="button" aria-label="Next track" onClick={() => m.playNext()}>⏭</button><button type="button" onClick={m.cycleRepeat}>Repeat {m.repeatMode}</button></div><div className="mu-seek"><span>{formatTime(m.currentTime)}</span><input aria-label="Track position" type="range" min="0" max={m.duration || 1} step=".1" disabled={!m.duration} value={Math.min(m.currentTime, m.duration || 1)} onChange={(e) => m.seekTo(Number(e.target.value))}/><span>{formatTime(m.duration)}</span></div></div><div className="mu-player-options"><label>Bitrate<select aria-label="Audio bitrate" value={m.quality} onChange={(e) => m.setQuality(e.target.value)}>{m.qualityChips.map((q) => <option key={q.id || q.key} value={q.id || q.key}>{q.label}</option>)}</select></label><label className="mu-volume">Volume<input aria-label="Music volume" type="range" min="0" max="1" step=".05" value={m.volume} onChange={(e) => m.changeVolume(e.target.value)}/></label><button type="button" onClick={() => setQueueOpen(true)}>Queue</button><button type="button" onClick={m.toggleListeningMode}>{m.listeningMode ? 'Keep awake: on' : 'Keep awake'}</button></div>
        {m.error && m.playerStatus === 'error' ? <div role="alert" className="mu-player-error">{m.error}<button type="button" onClick={m.retryTrack}>Retry track</button><button type="button" onClick={() => m.playNext()}>Skip</button></div> : null}
      </footer>
      {queueOpen ? <div className="mu-drawer-backdrop" onClick={() => setQueueOpen(false)}><section role="dialog" aria-modal="true" aria-label="Music queue" className="mu-queue-drawer" onClick={(e) => e.stopPropagation()}><header><h2>Up next · {m.queueTracks.length}</h2><button type="button" onClick={() => setQueueOpen(false)}>Close ✕</button></header><TrackList tracks={m.queueTracks} music={m}/>{!m.queueTracks.length ? <p className="mu-inline-state">Play an album or add tracks to build your queue.</p> : null}</section></div> : null}
    </main>
  );
}
